name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder'

      - name: Adding known hosts
        run: ssh-keyscan -H 13.61.97.26 >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz --delete ./ ec2-user@13.61.97.26:/tmp/website-temp/
          ssh ec2-user@13.61.97.26 'sudo cp -r /tmp/website-temp/* /usr/share/nginx/html/ && sudo chown -R nginx:nginx /usr/share/nginx/html/ && sudo chmod -R 755 /usr/share/nginx/html/'
          
